/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;
import napakalaki.CombatResult;
import napakalaki.Napakalaki;

/**
 *
 * @author Alexis
 */
public class NapakalakiView extends javax.swing.JFrame {

    /**
     * Creates new form NapakalakiView
     */
    private Napakalaki napakalakiModel;
    
    public NapakalakiView() {
        initComponents();
    }
    
    public void setNapakalaki(Napakalaki napa){
        this.napakalakiModel = napa;
        this.monsterView1.setVisible(false);
        this.monsterView1.setNapakalaki(napakalakiModel);
        this.playerView1.setNapakalaki(napakalakiModel);
        this.monsterView1.setMonster(napakalakiModel.getCurrentMonster());
        this.playerView1.setPlayer(napakalakiModel.getCurrentPlayer());
        repaint();
        revalidate();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monsterView1 = new GUI.MonsterView();
        jLabel1 = new javax.swing.JLabel();
        meetMonsterB = new javax.swing.JButton();
        combatB = new javax.swing.JButton();
        nextTurnB = new javax.swing.JButton();
        combatResult = new javax.swing.JLabel();
        canIPass = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        playerView1 = new GUI.PlayerView();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("COMBATE");

        meetMonsterB.setText("Meet Monster");
        meetMonsterB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meetMonsterBActionPerformed(evt);
            }
        });

        combatB.setText("Combat!");
        combatB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combatBActionPerformed(evt);
            }
        });

        nextTurnB.setText("Next Turn");
        nextTurnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextTurnBActionPerformed(evt);
            }
        });

        combatResult.setText("....");

        canIPass.setText("....");

        jButton1.setText("EXIT GAME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel2.setText("Result:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel3.setText("Next Turn?:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(monsterView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(meetMonsterB, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(48, 48, 48)
                                        .addComponent(combatB, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(nextTurnB)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1)))
                                .addGap(298, 298, 298))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(combatResult))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(canIPass)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(monsterView1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(meetMonsterB)
                            .addComponent(combatB)
                            .addComponent(nextTurnB)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(combatResult)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(canIPass)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meetMonsterBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meetMonsterBActionPerformed
        this.monsterView1.setVisible(true);
        this.combatB.setEnabled(true);
        this.meetMonsterB.setEnabled(false);
        this.playerView1.DisableStealTreasure();
        this.playerView1.DisableMakeVisible();
        repaint();
        revalidate();
    }//GEN-LAST:event_meetMonsterBActionPerformed

    private void combatBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combatBActionPerformed
        CombatResult cr = this.napakalakiModel.developCombat();
        String msg = "";
            
        switch(cr){    
            case LOSE:
                msg = "Has perdido el combate, te toca cumplir el mal rollo.";
            break;
                 
            case WIN:
                msg = "Has ganado el combate!!";
            break;
                    
            case WINGAME:
                msg = "Has ganado el juego!!!";
                this.combatB.setEnabled(false);
                this.meetMonsterB.setEnabled(false);
                this.nextTurnB.setEnabled(false);
                this.playerView1.DisableAllButtons();
            break;
                
            case LOSEANDCONVERT:
                msg = "Has perdido el combate, Ahora eres un jugador sectario.";
            break;
            
            default:
                    System.exit(0);
            break;
        }
        
        this.combatResult.setText(msg);
        
        if (cr != CombatResult.WINGAME) {
            playerView1.setPlayer(napakalakiModel.getCurrentPlayer());
            nextTurnB.setEnabled(true);
            combatB.setEnabled(false);
            playerView1.EnableStealTreasure();
            playerView1.EnableMakeVisible();
        }
    }//GEN-LAST:event_combatBActionPerformed

    private void nextTurnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextTurnBActionPerformed
        boolean canI = this.napakalakiModel.nextTurn();
        
        if(!canI)
            this.canIPass.setText("ERROR: No cumples las condiciones para pasar de turno, O bien tienes mas de 4 tesoros ocultos, O bien te queda mal rollo por cumplir.");
        else{
            playerView1.setPlayer(this.napakalakiModel.getCurrentPlayer());
            monsterView1.setMonster(napakalakiModel.getCurrentMonster());
            monsterView1.setVisible(false);
            this.combatResult.setText("Combar Result");
            combatB.setEnabled(false);
            meetMonsterB.setEnabled(true);
            nextTurnB.setEnabled(false);
            repaint();
            revalidate();
        }
    }//GEN-LAST:event_nextTurnBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void showView(){
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel canIPass;
    private javax.swing.JButton combatB;
    private javax.swing.JLabel combatResult;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton meetMonsterB;
    private GUI.MonsterView monsterView1;
    private javax.swing.JButton nextTurnB;
    private GUI.PlayerView playerView1;
    // End of variables declaration//GEN-END:variables
}
